CREATE TABLE IF NOT EXISTS yshop_material (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 type varchar(16), group_id varchar(64), name varchar(128), url varchar(1024),
 creator varchar(64) DEFAULT '', create_time timestamp DEFAULT CURRENT_TIMESTAMP,
 updater varchar(64) DEFAULT '', update_time timestamp DEFAULT CURRENT_TIMESTAMP,
 deleted bit DEFAULT FALSE
);
