package co.yixiang.yshop.module.order.payment;

import static org.junit.jupiter.api.Assertions.*;
import co.yixiang.yshop.module.pay.callback.*;
import co.yixiang.yshop.module.coupon.service.marketing.CouponLifecycle;
import org.junit.jupiter.api.*;
import java.util.*;

/** Trusted synthetic inbox/finalization only. This never addresses the development database. */
class CouponPaymentDatabaseTest {
    PaymentCancellationDatabaseTest fixture;
    PaymentDatabaseTest f;
    @BeforeEach void setup() throws Exception {
        fixture=new PaymentCancellationDatabaseTest();fixture.setup();f=fixture.f;
        f.jdbc.update("INSERT INTO yshop_coupon_user(id,user_id,status,reserved_order_id) VALUES(2,1,0,NULL)");
    }
    @AfterEach void close(){if(fixture!=null)fixture.close();}
    int n(String sql){return f.count(sql);}
    void redeemedOnce(){assertEquals(1,n("SELECT COUNT(*) FROM yshop_coupon_user WHERE id=1 AND redeemed_at IS NOT NULL AND redeemed_order_id='order-A' AND status=1"));assertEquals(0,n("SELECT COUNT(*) FROM yshop_coupon_user WHERE id=2 AND (status<>0 OR redeemed_at IS NOT NULL)"));assertEquals(1,n("SELECT COUNT(*) FROM yshop_coupon_operation WHERE kind='REDEEM'"));assertEquals(0,n("SELECT COUNT(*) FROM yshop_coupon_operation WHERE kind='RELEASE'"));}
    @Test void trustedSyntheticCompletionRedeemsOnlyTheOrderCoupon(){var a=fixture.create();var event=fixture.success(a);assertEquals(PaymentResult.FIRST_SUCCESS,f.service.acceptAttemptVerified(event));assertEquals(PaymentResult.IDEMPOTENT_DUPLICATE,f.service.acceptAttemptVerified(event));redeemedOnce();assertEquals("USED",new CouponLifecycle(f.jdbc).state(f.jdbc.queryForMap("SELECT * FROM yshop_coupon_user WHERE id=1"),java.time.LocalDateTime.now()));}
    @Test void inboxReceiptAloneDoesNotRedeem(){var a=fixture.create();f.ctx.getBean(co.yixiang.yshop.module.order.service.payment.PaymentInbox.class).captureAttempt(fixture.success(a),a);assertEquals(0,n("SELECT COUNT(*) FROM yshop_coupon_user WHERE redeemed_at IS NOT NULL"));assertEquals(0,n("SELECT COUNT(*) FROM yshop_coupon_operation"));fixture.blocked();}
    @Test void wrongCouponReservationMakesFinalizationRollback(){var a=fixture.create();f.jdbc.update("UPDATE yshop_coupon_user SET reserved_order_id='synthetic-other' WHERE id=1");assertEquals(PaymentResult.RETRY,f.service.acceptAttemptVerified(fixture.success(a)));assertEquals(0,n("SELECT paid FROM yshop_store_order WHERE order_id='order-A'"));assertEquals(0,n("SELECT COUNT(*) FROM yshop_coupon_user WHERE redeemed_at IS NOT NULL"));assertEquals(0,n("SELECT COUNT(*) FROM yshop_user_bill"));assertEquals(0,n("SELECT COUNT(*) FROM yshop_coupon_operation"));}
    @Test void redemptionFailureRollsBackFinancialEffectsThenRecoverySucceeds(){var a=fixture.create();var event=fixture.success(a);f.jdbc.execute("ALTER TABLE yshop_coupon_operation ADD CONSTRAINT injected_redeem_fault CHECK(kind<>'REDEEM')");assertEquals(PaymentResult.RETRY,f.service.acceptAttemptVerified(event));assertEquals(0,n("SELECT paid FROM yshop_store_order WHERE order_id='order-A'"));assertEquals(0,n("SELECT COUNT(*) FROM yshop_coupon_user WHERE redeemed_at IS NOT NULL"));assertEquals(0,n("SELECT COUNT(*) FROM yshop_user_bill"));assertEquals(0,n("SELECT COUNT(*) FROM yshop_coupon_operation"));f.jdbc.execute("ALTER TABLE yshop_coupon_operation "+(PaymentDatabaseTest.mysqlAcceptance()?"DROP CHECK ":"DROP CONSTRAINT ")+"injected_redeem_fault");assertEquals(PaymentResult.FIRST_SUCCESS,f.service.acceptAttemptVerified(event));redeemedOnce();}
    @Test void wrongAmountEventDoesNotRedeem(){var a=fixture.create();var valid=fixture.success(a);var bad=new PaymentSuccessEvent(valid.provider(),valid.merchantDetailsId(),valid.outTradeNo(),valid.providerTransactionId(),99,valid.appid(),valid.mchId(),valid.resultCode(),valid.receivedAt());assertEquals(PaymentResult.REJECTED,f.service.acceptAttemptVerified(bad));assertEquals(0,n("SELECT COUNT(*) FROM yshop_coupon_user WHERE redeemed_at IS NOT NULL"));assertEquals(0,n("SELECT paid FROM yshop_store_order WHERE order_id='order-A'"));}
    @Test void conflictDoesNotRedeemSecondCoupon(){var a=fixture.create();assertEquals(PaymentResult.FIRST_SUCCESS,f.service.acceptAttemptVerified(fixture.success(a)));redeemedOnce();f.jdbc.update("UPDATE yshop_store_order SET coupon_id=2 WHERE order_id='order-A'");var e=fixture.success(a);var other=new PaymentSuccessEvent(e.provider(),e.merchantDetailsId(),e.outTradeNo(),"synthetic-conflicting-transaction",e.totalFeeCents(),e.appid(),e.mchId(),e.resultCode(),e.receivedAt());assertNotEquals(PaymentResult.FIRST_SUCCESS,f.service.acceptAttemptVerified(other));redeemedOnce();}
    @Test void paidOrderCannotReturnCoupon(){var a=fixture.create();assertEquals(PaymentResult.FIRST_SUCCESS,f.service.acceptAttemptVerified(fixture.success(a)));assertThrows(RuntimeException.class,()->fixture.ordering.cancel("order-A",1L,false));redeemedOnce();}
    @Test void uncertainAttemptCannotReleaseEvenIfCouponExpired(){fixture.uncertain();f.jdbc.update("UPDATE yshop_coupon_user SET end_time='2020-01-02' WHERE id=1");fixture.blocked();assertEquals(0,n("SELECT COUNT(*) FROM yshop_coupon_operation"));}
    @RepeatedTest(20) void twentySyntheticSuccessEventsRedeemExactlyOnce() throws Exception {var a=fixture.create();var event=fixture.success(a);var results=fixture.concurrent(20,i->f.service.acceptAttemptVerified(event));assertEquals(1,Collections.frequency(results,PaymentResult.FIRST_SUCCESS));assertEquals(19,Collections.frequency(results,PaymentResult.IDEMPOTENT_DUPLICATE));redeemedOnce();}
    @RepeatedTest(20) void syntheticPaymentAndCancellationNoDuplicateRelease() throws Exception {var a=fixture.create();var event=fixture.success(a);var results=fixture.concurrent(20,i->{if(i%2==0)return f.service.acceptAttemptVerified(event).name();try{fixture.ordering.cancel("order-A",1L,false);throw new AssertionError("ACTIVE_PAYMENT_MUST_BLOCK_CANCEL");}catch(co.yixiang.yshop.framework.common.exception.ServiceException blocked){return "blocked";}});assertTrue(results.contains("FIRST_SUCCESS"));redeemedOnce();assertEquals(9,n("SELECT stock FROM yshop_store_product"));}
    @RepeatedTest(20) void terminalLateSuccessDoesNotRedeemOrRestoreAgain() throws Exception {var a=fixture.uncertain();fixture.remote(a,"CLOSED");fixture.ordering.cancel("order-A",1L,false);var event=fixture.success(a);fixture.concurrent(20,i->{if(i%2==0)return f.service.acceptAttemptVerified(event).name();try{fixture.ordering.cancel("order-A",1L,false);return "cancel-retry";}catch(co.yixiang.yshop.framework.common.exception.ServiceException blocked){return "blocked";}});assertEquals(0,n("SELECT COUNT(*) FROM yshop_coupon_user WHERE redeemed_at IS NOT NULL"));assertEquals(1,n("SELECT COUNT(*) FROM yshop_coupon_operation WHERE kind='RELEASE'"));assertEquals(0,n("SELECT COUNT(*) FROM yshop_coupon_operation WHERE kind='REDEEM'"));assertEquals(0,n("SELECT paid FROM yshop_store_order WHERE order_id='order-A'"));assertEquals(10,n("SELECT stock FROM yshop_store_product"));}
}
