package co.yixiang.yshop.module.order.payment;

import static org.junit.jupiter.api.Assertions.*;

import co.yixiang.yshop.module.order.service.ordering.*;
import co.yixiang.yshop.module.order.service.payment.*;
import co.yixiang.yshop.module.order.service.payment.attempt.*;
import co.yixiang.yshop.module.pay.callback.*;

import org.junit.jupiter.api.*;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.springframework.transaction.*;
import org.springframework.transaction.support.TransactionTemplate;

import java.time.LocalDateTime;
import java.util.*;
import java.util.concurrent.*;

/** Production cancellation, attempt services, MyBatis and finalization; synthetic isolated data. */
class PaymentCancellationDatabaseTest {
    PaymentDatabaseTest f;
    PaymentAttemptService attempts;
    OrderPlacementService ordering;
    PlatformTransactionManager tm;
    static final List<String> EXTRA =
            List.of(
                    "yshop_store_product",
                    "yshop_store_product_attr_value",
                    "yshop_coupon_user",
                    "yshop_order_inventory_reservation");
    static final List<String> SNAPSHOT =
            List.of(
                    "yshop_store_order",
                    "yshop_store_product",
                    "yshop_store_product_attr_value",
                    "yshop_coupon_user",
                    "yshop_order_inventory_reservation",
                    "yshop_store_order_status",
                    "yshop_order_payment_attempt",
                    "yshop_order_payment",
                    "yshop_order_payment_conflict",
                    "yshop_member_wallet_transaction",
                    "yshop_member_recharge_order",
                    "yshop_user_bill",
                    "yshop_user");

    @BeforeEach
    void setup() throws Exception {
        f = new PaymentDatabaseTest();
        f.setup();
        if (!PaymentDatabaseTest.mysqlAcceptance())
            f.jdbc.execute(
                    "ALTER TABLE yshop_store_order_status ALTER COLUMN id BIGINT GENERATED BY"
                            + " DEFAULT AS IDENTITY");
        tm = f.ctx.getBean(PlatformTransactionManager.class);
        attempts = f.ctx.getBean(PaymentAttemptService.class);
        ordering = new OrderPlacementService(f.jdbc, tm, new PaymentCancellationGuard(f.jdbc));
        for (String t : EXTRA) f.jdbc.execute("DROP TABLE IF EXISTS " + t);
        f.jdbc.execute(
                "ALTER TABLE yshop_store_order ADD COLUMN ordering_version INT NOT NULL DEFAULT 0");
        f.jdbc.execute(
                "CREATE TABLE yshop_store_product(id BIGINT PRIMARY KEY,shop_id BIGINT,stock"
                        + " INT,sales INT)");
        f.jdbc.execute(
                "CREATE TABLE yshop_store_product_attr_value(id BIGINT PRIMARY KEY,product_id"
                        + " BIGINT,stock INT,sales INT)");
        f.jdbc.execute(
                "CREATE TABLE yshop_coupon_user(id BIGINT PRIMARY KEY,user_id BIGINT,status"
                        + " INT,reserved_order_id VARCHAR(32))");
        f.jdbc.execute(
                "CREATE TABLE yshop_order_inventory_reservation(order_id VARCHAR(32),line_no"
                        + " INT,product_id BIGINT,sku_id BIGINT,quantity INT,released_at"
                        + " TIMESTAMP,PRIMARY KEY(order_id,line_no))");
        f.jdbc.update(
                "UPDATE yshop_store_order SET ordering_version=1,shop_id=1,create_time=? WHERE"
                        + " order_id='order-A'",
                LocalDateTime.now().minusMinutes(31));
        if (PaymentDatabaseTest.mysqlAcceptance()) {
            var engine =
                    f.jdbc.queryForMap(
                            "SELECT COUNT(*) AS total,SUM(ENGINE='InnoDB') AS innodb FROM"
                                    + " information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE()");
            assertEquals(16, ((Number) engine.get("total")).intValue());
            assertEquals(16, ((Number) engine.get("innodb")).intValue());
        }
        f.jdbc.update("INSERT INTO yshop_store_product VALUES(1,1,9,1)");
        f.jdbc.update("INSERT INTO yshop_store_product_attr_value VALUES(1,1,9,1)");
        f.jdbc.update("INSERT INTO yshop_coupon_user VALUES(1,1,1,'order-A')");
        f.jdbc.update(
                "INSERT INTO yshop_order_inventory_reservation VALUES('order-A',0,1,1,1,NULL)");
    }

    @AfterEach
    void close() {
        if (f != null) {
            for (String t : EXTRA) f.jdbc.execute("DROP TABLE IF EXISTS " + t);
            f.close();
        }
    }

    PaymentAttempt create() {
        return attempts.createOrGet(
                1L,
                "order-A",
                PaymentSuccessEvent.Provider.WECHAT,
                "merchant-wx",
                "synthetic-cancel");
    }

    PaymentAttempt uncertain() {
        var a = create();
        assertTrue(attempts.claimPrepay(1L, a.getAttemptId()));
        return attempts.read(1L, a.getAttemptId());
    }

    void remote(PaymentAttempt a, String state) {
        String token = UUID.randomUUID().toString().replace("-", "");
        assertNotNull(attempts.claimReconciliation(a.getAttemptId(), token, 60, 0));
        assertTrue(attempts.confirmRemoteTerminal(a.getAttemptId(), token, state));
    }

    PaymentSuccessEvent success(PaymentAttempt a) {
        return new PaymentSuccessEvent(
                PaymentSuccessEvent.Provider.WECHAT,
                a.getMerchantDetailsId(),
                a.getProviderOrderReference(),
                "synthetic-cancel-payment",
                a.getAmountCents(),
                a.getAppid(),
                a.getMerchantIdentity(),
                "SUCCESS",
                LocalDateTime.now());
    }

    Map<String, List<Map<String, Object>>> snapshot() {
        Map<String, List<Map<String, Object>>> s = new LinkedHashMap<>();
        for (String t : SNAPSHOT)
            s.put(t, f.jdbc.queryForList("SELECT * FROM " + t + " ORDER BY 1"));
        return s;
    }

    void blocked() {
        var before = snapshot();
        assertThrows(RuntimeException.class, () -> ordering.cancel("order-A", 1L, false));
        assertEquals(before, snapshot());
        assertEquals(0, ordering.expireBatch());
        assertEquals(before, snapshot());
    }

    void canceled() {
        assertEquals(
                1, f.count("SELECT COUNT(*) FROM yshop_store_order WHERE deleted=1 AND paid=0"));
        assertEquals(10, f.count("SELECT stock FROM yshop_store_product"));
        assertEquals(10, f.count("SELECT stock FROM yshop_store_product_attr_value"));
        assertEquals(0, f.count("SELECT status FROM yshop_coupon_user"));
        assertEquals(
                1,
                f.count(
                        "SELECT COUNT(*) FROM yshop_order_inventory_reservation WHERE released_at"
                                + " IS NOT NULL"));
        assertEquals(
                1,
                f.count(
                        "SELECT COUNT(*) FROM yshop_store_order_status WHERE"
                                + " change_type='cancel_order'"));
        assertEquals(0, f.count("SELECT COUNT(*) FROM yshop_member_wallet_transaction"));
    }

    <T> List<T> concurrent(int n, java.util.function.IntFunction<T> action) throws Exception {
        var pool = Executors.newFixedThreadPool(n);
        var gate = new CountDownLatch(1);
        try {
            List<Future<T>> futures = new ArrayList<>();
            for (int i = 0; i < n; i++) {
                int index = i;
                futures.add(
                        pool.submit(
                                () -> {
                                    gate.await();
                                    return action.apply(index);
                                }));
            }
            gate.countDown();
            List<T> results = new ArrayList<>();
            for (var future : futures) results.add(future.get(45, TimeUnit.SECONDS));
            return results;
        } finally {
            pool.shutdownNow();
            assertTrue(pool.awaitTermination(10, TimeUnit.SECONDS));
        }
    }

    @Test
    void noAttemptCancelsAndRetryReleasesExactlyOnce() {
        ordering.cancel("order-A", 1L, false);
        var before = snapshot();
        ordering.cancel("order-A", 1L, false);
        assertEquals(before, snapshot());
        canceled();
    }

    @ParameterizedTest
    @ValueSource(strings = {"CREATED", "UNCERTAIN", "PREPAY_CREATED"})
    void activeOrUncertainBlocksCustomerAndExpiry(String kind) {
        var a = create();
        if (!kind.equals("CREATED")) assertTrue(attempts.claimPrepay(1L, a.getAttemptId()));
        if (kind.equals("PREPAY_CREATED"))
            attempts.recordPrepay(1L, a.getAttemptId(), "synthetic-prepay");
        blocked();
    }

    @ParameterizedTest
    @ValueSource(strings = {"FAILED", "EXPIRED", "CANCELED"})
    void explicitlyTerminatedNeverRequestedAttemptAllowsCancel(String state) {
        var a = create();
        attempts.terminateCreated(1L, a.getAttemptId(), PaymentAttemptState.valueOf(state));
        var history = f.jdbc.queryForList("SELECT * FROM yshop_order_payment_attempt");
        ordering.cancel("order-A", 1L, false);
        canceled();
        assertEquals(history, f.jdbc.queryForList("SELECT * FROM yshop_order_payment_attempt"));
    }

    PaymentAttempt unprovedTerminal(String state) {
        String id = UUID.randomUUID().toString().replace("-", "");
        // Synthetic historical metadata insert; do not disable or bypass immutable UPDATE triggers.
        f.jdbc.update(
                "INSERT INTO"
                    + " yshop_order_payment_attempt(attempt_id,order_id,uid,idempotency_key,provider,merchant_details_id,amount_cents,currency,appid,merchant_identity,provider_order_reference,status,prepay_requested_at)"
                    + " VALUES(?,'order-A',1,?,'WECHAT','merchant-wx',2,'CNY','synthetic-app','synthetic-merchant',?,?,CURRENT_TIMESTAMP)",
                id,
                id,
                id,
                state);
        return attempts.read(1L, id);
    }

    @ParameterizedTest
    @ValueSource(strings = {"FAILED", "EXPIRED", "CANCELED"})
    void localTerminalCannotProveRequestedPaymentSafe(String state) {
        unprovedTerminal(state);
        blocked();
    }

    @ParameterizedTest
    @ValueSource(strings = {"CLOSED", "REVOKED", "PAYERROR"})
    void trustedRemoteTerminalAllowsCancel(String state) {
        var a = uncertain();
        remote(a, state);
        var history = f.jdbc.queryForList("SELECT * FROM yshop_order_payment_attempt");
        ordering.cancel("order-A", 1L, false);
        canceled();
        assertEquals(history, f.jdbc.queryForList("SELECT * FROM yshop_order_payment_attempt"));
    }

    @Test
    void oldUnsafeAttemptNotHiddenByNewerSafeHistory() {
        unprovedTerminal("EXPIRED");
        var newer =
                attempts.createOrGet(
                        1L,
                        "order-A",
                        PaymentSuccessEvent.Provider.WECHAT,
                        "merchant-wx",
                        "second-synthetic");
        attempts.terminateCreated(1L, newer.getAttemptId(), PaymentAttemptState.CANCELED);
        blocked();
    }

    @Test
    void blockedThenRemoteConfirmedRetryWorks() {
        var a = uncertain();
        blocked();
        remote(a, "CLOSED");
        ordering.cancel("order-A", 1L, false);
        ordering.cancel("order-A", 1L, false);
        canceled();
    }

    @Test
    void expiryUsesSameAdmissionAndCanRetryAfterProof() {
        var a = uncertain();
        var before = snapshot();
        new UnpaidOrderExpiry(ordering).expire();
        assertEquals(before, snapshot());
        remote(a, "CLOSED");
        assertEquals(1, ordering.expireBatch());
        assertEquals(0, ordering.expireBatch());
        canceled();
    }

    @Test
    void paidOrderCannotCancelOrExpire() {
        var a = create();
        assertEquals(PaymentResult.FIRST_SUCCESS, f.service.acceptAttemptVerified(success(a)));
        blocked();
        assertEquals("PAID", attempts.read(1L, a.getAttemptId()).getStatus());
        f.effects(1);
    }

    @Test
    void lateSuccessAfterRemoteCloseBlocksCancellation() {
        var a = uncertain();
        remote(a, "CLOSED");
        assertEquals(
                PaymentResult.RECONCILIATION_REQUIRED, f.service.acceptAttemptVerified(success(a)));
        blocked();
        f.effects(0);
    }

    @Test
    void legacyConflictBlocksEvenRemoteClosedAttempt() {
        var a = uncertain();
        remote(a, "CLOSED");
        assertEquals(PaymentResult.REJECTED, f.pay());
        assertEquals(
                1,
                f.count(
                        "SELECT COUNT(*) FROM yshop_order_payment WHERE"
                                + " status='PAYMENT_CONFLICT'"));
        blocked();
    }

    @Test
    void independentConflictEvidenceBlocksWithoutActiveAttempt() {
        f.pay();
        f.order("order-B", 2);
        assertEquals(
                PaymentResult.REJECTED, f.service.accept(f.event("order-B", "synthetic-T1", 2)));
        var guard = new PaymentCancellationGuard(f.jdbc);
        var tx = new TransactionTemplate(tm);
        tx.setIsolationLevel(TransactionDefinition.ISOLATION_READ_COMMITTED);
        var before = snapshot();
        assertThrows(
                RuntimeException.class,
                () ->
                        tx.executeWithoutResult(
                                x -> {
                                    f.orders.lockPaymentOrder("order-B");
                                    guard.assertSafeAfterOrderLock("order-B");
                                }));
        assertEquals(before, snapshot());
    }

    @Test
    void receivedSuccessIsNotCanceledBeforeProcessing() {
        var a = uncertain();
        remote(a, "CLOSED");
        f.ctx.getBean(PaymentInbox.class)
                .captureAttempt(success(a), attempts.read(1L, a.getAttemptId()));
        blocked();
    }

    @Test
    void missingFinancialSchemaFailsClosed() {
        f.jdbc.execute("DROP TABLE yshop_order_payment_attempt");
        var before = f.jdbc.queryForList("SELECT * FROM yshop_order_inventory_reservation");
        assertThrows(RuntimeException.class, () -> ordering.cancel("order-A", 1L, false));
        assertEquals(
                before, f.jdbc.queryForList("SELECT * FROM yshop_order_inventory_reservation"));
        assertEquals(0, f.count("SELECT COUNT(*) FROM yshop_store_order WHERE deleted=1"));
    }

    @Test
    void repeatableReadCallerIsRejectedBeforeAnyWrites() {
        var before = snapshot();
        var tx = new TransactionTemplate(tm);
        tx.setIsolationLevel(TransactionDefinition.ISOLATION_REPEATABLE_READ);
        assertThrows(
                RuntimeException.class,
                () -> tx.executeWithoutResult(x -> ordering.cancel("order-A", 1L, false)));
        assertEquals(before, snapshot());
    }

    @Test
    void legacyCancellationAlsoBlocksActiveAttempt() {
        uncertain();
        var before = snapshot();
        assertThrows(RuntimeException.class, () -> f.cancelService().cancelOrder("order-A", 1L));
        assertEquals(before, snapshot());
    }

    @RepeatedTest(20)
    void cancellationAndAttemptCreationRace() throws Exception {
        var result =
                concurrent(
                        20,
                        i -> {
                            if (i % 2 == 0) {
                                try {
                                    create();
                                    return "attempt";
                                } catch (IllegalStateException rejected) {
                                    assertEquals("ORDER_NOT_PAYABLE", rejected.getMessage());
                                    return "attempt-rejected";
                                }
                            }
                            try {
                                ordering.cancel("order-A", 1L, false);
                                return "cancel";
                            } catch (
                                    co.yixiang.yshop.framework.common.exception.ServiceException
                                            rejected) {
                                assertEquals(
                                        "PAYMENT_ATTEMPT_PREVENTS_CANCELLATION",
                                        rejected.getMessage());
                                return "cancel-rejected";
                            }
                        });
        assertEquals(20, result.size());
        if (f.count("SELECT COUNT(*) FROM yshop_order_payment_attempt") > 0) {
            assertEquals(0, f.count("SELECT COUNT(*) FROM yshop_store_order WHERE deleted=1"));
            assertEquals(9, f.count("SELECT stock FROM yshop_store_product"));
            assertEquals(1, f.count("SELECT status FROM yshop_coupon_user"));
        } else canceled();
    }

    @RepeatedTest(20)
    void callbackAndCancelRaceDoesNotDeadlock() throws Exception {
        var a = create();
        var event = success(a);
        var result =
                concurrent(
                        20,
                        i -> {
                            if (i % 2 == 0) return f.service.acceptAttemptVerified(event).name();
                            try {
                                ordering.cancel("order-A", 1L, false);
                                throw new AssertionError(
                                        "Active attempt must prevent cancellation");
                            } catch (RuntimeException blocked) {
                                return "blocked";
                            }
                        });
        assertTrue(result.contains("FIRST_SUCCESS"));
        assertEquals(0, f.count("SELECT COUNT(*) FROM yshop_store_order WHERE deleted=1"));
        assertEquals(9, f.count("SELECT stock FROM yshop_store_product"));
        assertEquals(1, f.count("SELECT status FROM yshop_coupon_user"));
        f.effects(1);
    }

    @RepeatedTest(20)
    void expiryAndAttemptCreationRace() throws Exception {
        concurrent(
                20,
                i -> {
                    if (i % 2 == 0) {
                        try {
                            create();
                            return "attempt";
                        } catch (IllegalStateException rejected) {
                            assertEquals("ORDER_NOT_PAYABLE", rejected.getMessage());
                            return "attempt-rejected";
                        }
                    }
                    return "expired:" + ordering.expireBatch();
                });
        if (f.count("SELECT COUNT(*) FROM yshop_order_payment_attempt") > 0) {
            assertEquals(0, f.count("SELECT COUNT(*) FROM yshop_store_order WHERE deleted=1"));
            assertEquals(9, f.count("SELECT stock FROM yshop_store_product"));
            assertEquals(1, f.count("SELECT status FROM yshop_coupon_user"));
        } else canceled();
    }

    @Test
    void prepayClaimAndCancelRaceNeverReleasesInventory() throws Exception {
        var a = create();
        var result =
                concurrent(
                        20,
                        i -> {
                            if (i % 2 == 0)
                                return attempts.claimPrepay(1L, a.getAttemptId())
                                        ? "claimed"
                                        : "already-claimed";
                            var failure =
                                    assertThrows(
                                            co.yixiang.yshop.framework.common.exception
                                                    .ServiceException.class,
                                            () -> ordering.cancel("order-A", 1L, false));
                            assertEquals(
                                    "PAYMENT_ATTEMPT_PREVENTS_CANCELLATION", failure.getMessage());
                            return "blocked";
                        });
        assertEquals(1, result.stream().filter("claimed"::equals).count());
        blocked();
    }

    @Test
    void remoteProofAndCancelRaceReleasesOnlyAfterConfirmation() throws Exception {
        var a = uncertain();
        String token = UUID.randomUUID().toString().replace("-", "");
        assertNotNull(attempts.claimReconciliation(a.getAttemptId(), token, 60, 0));
        concurrent(
                20,
                i -> {
                    if (i == 0) {
                        assertTrue(
                                attempts.confirmRemoteTerminal(a.getAttemptId(), token, "CLOSED"));
                        return "proof";
                    }
                    try {
                        ordering.cancel("order-A", 1L, false);
                        return "canceled";
                    } catch (co.yixiang.yshop.framework.common.exception.ServiceException blocked) {
                        assertEquals("PAYMENT_ATTEMPT_PREVENTS_CANCELLATION", blocked.getMessage());
                        return "deferred";
                    }
                });
        ordering.cancel("order-A", 1L, false);
        canceled();
        assertNotNull(attempts.read(1L, a.getAttemptId()).getRemoteConfirmedAt());
    }

    @RepeatedTest(20)
    void lateSuccessAfterProofRacesCancelWithoutFulfillment() throws Exception {
        var a = uncertain();
        remote(a, "CLOSED");
        var event = success(a);
        concurrent(
                20,
                i -> {
                    if (i % 2 == 0) {
                        assertEquals(
                                PaymentResult.RECONCILIATION_REQUIRED,
                                f.service.acceptAttemptVerified(event));
                        return "reconciliation";
                    }
                    try {
                        ordering.cancel("order-A", 1L, false);
                        return "canceled";
                    } catch (co.yixiang.yshop.framework.common.exception.ServiceException blocked) {
                        assertEquals("PAYMENT_REVIEW_PREVENTS_CANCELLATION", blocked.getMessage());
                        return "deferred";
                    }
                });
        f.effects(0);
        assertEquals(0, f.count("SELECT paid FROM yshop_store_order WHERE order_id='order-A'"));
        assertEquals("CANCELED", attempts.read(1L, a.getAttemptId()).getStatus());
        if (f.count("SELECT COUNT(*) FROM yshop_store_order WHERE deleted=1") == 1) canceled();
        else {
            assertEquals(9, f.count("SELECT stock FROM yshop_store_product"));
            assertEquals(1, f.count("SELECT status FROM yshop_coupon_user"));
            blocked();
        }
    }

    @Test
    void receiptLockIsNeverAcquiredAfterOrderLock() throws Exception {
        var a = uncertain();
        remote(a, "CLOSED");
        var receipt =
                f.ctx.getBean(PaymentInbox.class)
                        .captureAttempt(success(a), attempts.read(1L, a.getAttemptId()));
        var orderLocked = new CountDownLatch(1);
        var eventLocked = new CountDownLatch(1);
        var pool = Executors.newFixedThreadPool(2);
        try {
            var cancel =
                    pool.submit(
                            () -> {
                                var tx = new TransactionTemplate(tm);
                                tx.setIsolationLevel(
                                        TransactionDefinition.ISOLATION_READ_COMMITTED);
                                assertThrows(
                                        org.springframework.transaction.UnexpectedRollbackException
                                                .class,
                                        () ->
                                                tx.executeWithoutResult(
                                                        x -> {
                                                            f.orders.lockPaymentOrder("order-A");
                                                            orderLocked.countDown();
                                                            try {
                                                                assertTrue(
                                                                        eventLocked.await(
                                                                                10,
                                                                                TimeUnit.SECONDS));
                                                            } catch (InterruptedException e) {
                                                                throw new RuntimeException(e);
                                                            }
                                                            assertThrows(
                                                                    RuntimeException.class,
                                                                    () ->
                                                                            ordering.cancel(
                                                                                    "order-A", 1L,
                                                                                    false));
                                                        }));
                            });
            var process =
                    pool.submit(
                            () -> {
                                try {
                                    assertTrue(orderLocked.await(10, TimeUnit.SECONDS));
                                } catch (InterruptedException e) {
                                    throw new RuntimeException(e);
                                }
                                new TransactionTemplate(tm)
                                        .executeWithoutResult(
                                                x -> {
                                                    f.payments.lockEvent(receipt.id());
                                                    eventLocked.countDown();
                                                    assertEquals(
                                                            PaymentResult.RECONCILIATION_REQUIRED,
                                                            f.ctx.getBean(PaymentProcessor.class)
                                                                    .process(receipt.id(), false));
                                                });
                            });
            cancel.get(20, TimeUnit.SECONDS);
            process.get(20, TimeUnit.SECONDS);
            blocked();
        } finally {
            pool.shutdownNow();
            assertTrue(pool.awaitTermination(10, TimeUnit.SECONDS));
        }
    }

    @Test
    void currentReadSeesReceiptCommittedAfterEarlierCallerRead() throws Exception {
        var a = uncertain();
        remote(a, "CLOSED");
        var pool = Executors.newSingleThreadExecutor();
        try {
            var tx = new TransactionTemplate(tm);
            tx.setIsolationLevel(TransactionDefinition.ISOLATION_READ_COMMITTED);
            assertThrows(
                    org.springframework.transaction.UnexpectedRollbackException.class,
                    () ->
                            tx.executeWithoutResult(
                                    x -> {
                                        f.count("SELECT COUNT(*) FROM yshop_order_payment");
                                        try {
                                            pool.submit(
                                                            () ->
                                                                    f.ctx.getBean(
                                                                                    PaymentInbox
                                                                                            .class)
                                                                            .captureAttempt(
                                                                                    success(a),
                                                                                    attempts.read(
                                                                                            1L,
                                                                                            a
                                                                                                    .getAttemptId())))
                                                    .get(10, TimeUnit.SECONDS);
                                        } catch (Exception e) {
                                            throw new RuntimeException(e);
                                        }
                                        assertThrows(
                                                RuntimeException.class,
                                                () -> ordering.cancel("order-A", 1L, false));
                                    }));
            blocked();
        } finally {
            pool.shutdownNow();
        }
    }
}
